### ISSUE TITLE
enhancement 

### ISSUE THREAD

**Issue by 2531** [shapoco/calctus#1]
考虑添加指定进制转换功能吗？

**Comment by shapoco** [comment]
Thanks for the suggestion, I'm looking into the possibility of converting when the Tab key or something is pressed.

**Comment by 2531** [comment]
Thank you for the reply, looking forward to your creative.

**Comment by shapoco** [comment]
Radix Mode buttons added.
https://github.com/shapoco/calctus/releases/tag/v0.0.8362.27168-alpha
