### ISSUE TITLE
solver issue @v0.6.8752.1500(alpha)

### ISSUE THREAD

**Issue by yukimaru73** [shapoco/calctus#100]
![image](https://github.com/shapoco/calctus/assets/16848674/a9ef03bc-f9b4-42b4-a8da-0194b5e816f7)

**Comment by shapoco** [comment]
In v0.6, the use of the solve function was changed to giving a function name or lambda expression.

```c++
def f(x)=x^2-2
solve(f) // --> [-1.414213562, 1.414213562].
solve(x=>x^2-2) // This gives the same result.
```
