### ISSUE TITLE
weird calculation fail

### ISSUE THREAD

**Issue by Nigh** [shapoco/calctus#104]
![Screenshot 2024-04-18 193938](https://github.com/shapoco/calctus/assets/1407471/825bc6f3-4bd6-4c46-b97d-7d20e5516d8d)

In this picture, the `1 - pow(2, -10*x)` cannot calulate while the every element in the `x` array could be calclate with the same expression.

**Comment by shapoco** [comment]
In the current version, only the first argument of the `pow()` can accept an array. You can see which arguments can accept arrays in the candidate completion list.

![image](https://github.com/shapoco/calctus/assets/40152459/2579c9e1-cf27-49b7-9fca-0f952accaf6a)

If you want to give an array as the second argument, which is not cool, such a function can be defined as follows:

```
pow(2,[1,2,3]) // --> Error
def mypow(x,*y)=pow(x,y)
mypow(2,[1,2,3]) // --> [2, 4, 8]
```

**Comment by Nigh** [comment]
Understood, thx.
