### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 2531** [shapoco/calctus#17]
Is it possible to add the two features below, thank you in advance.
1. Window Top
2. Add separator for long numbers, Comma or space
![image](https://user-images.githubusercontent.com/35393173/204786535-323ae62e-e68d-45a3-86b0-a564b9097ff5.png)

**Comment by shapoco** [comment]
1. "always on top" button will be available from next version.
2. Would like to support in the future.

**Comment by 2531** [comment]
It would be nice to add function suggestions and parentheses auto-completion, just like programming.😊

**Comment by shapoco** [comment]
Auto-completion was reflected in v0.2.8527.34374-beta.
