### ISSUE TITLE
Some problems with UnitSystem

### ISSUE THREAD

**Issue by nulta** [shapoco/calctus#18]
ver: 0.0.8370.36583

- [ ] Expressions containing unit doesn't respect `Max length of decimal place to display` settings
![image](https://user-images.githubusercontent.com/35414766/205113107-37fa37a7-035d-4f31-b457-097574f1ac58.png)

- [ ] [degC] is not converted to [K] properly
![image](https://user-images.githubusercontent.com/35414766/205114160-468f91c9-ac65-4c6a-a854-20ea072ef42c.png)

- [ ] Dimension units like m² cannot be solved with `[m2]`, but output text is `[m2]`
![image](https://user-images.githubusercontent.com/35414766/205116932-e237f68b-b940-4499-97e3-9098fc634610.png)

- [ ] It would be good if we can select/convert the output ScaledUnit
![image](https://user-images.githubusercontent.com/35414766/205116175-b855a80c-5329-40eb-bd10-b092b71dff1a.png)

also, thank you for developing!!

**Comment by shapoco** [comment]
Thank you for pointing this out.
The unit system functionality has not been tested and has many bugs.
I may remove the unit system feature as it may conflict with features that will be added in the future.

**Comment by shapoco** [comment]
Unit system functionality has been removed.
