### ISSUE TITLE
Ability to copy current & history results

### ISSUE THREAD

**Issue by 1357310795** [shapoco/calctus#2]
## Description
I want to copy history expressions and results to use in current expression. But as I clicked history results and back, the current expression was emptied. 

![image](https://user-images.githubusercontent.com/35869804/180345144-eda98858-4869-43ab-bb34-93910a82ed4b.png)

![image](https://user-images.githubusercontent.com/35869804/180345156-532ccf92-1a5b-4696-89e8-fc16be017b4b.png)

![image](https://user-images.githubusercontent.com/35869804/180345167-3a1db5ca-2c1a-4249-9c23-313a8d499610.png)

## Expected
- Do not clear current expression
- Add context menus to history results for quick copy results
- Add a way to copy the current result

**Comment by shapoco** [comment]
fixed: undetermined equation not to be lost. 
https://github.com/shapoco/calctus/releases/tag/v0.0.8362.27168-alpha
