### ISSUE TITLE
Want to delete some history

### ISSUE THREAD

**Issue by crazypeace** [shapoco/calctus#3]
Want to delete some history. 
That will make the whole calculation clearer.
![2022-07-24_21-34-26](https://user-images.githubusercontent.com/665889/180649438-9884bbac-0ef3-49bc-bccc-fb76bcd304c8.png)

**Comment by shapoco** [comment]
delete function added to context menu at https://github.com/shapoco/calctus/commit/bb7082b9de1ed20a9f161a2d3f177fabc864b795
