### ISSUE TITLE
Want to drag the history to adjust the sequennce

### ISSUE THREAD

**Issue by crazypeace** [shapoco/calctus#4]
Want to drag the history to adjust the sequennce
![image](https://user-images.githubusercontent.com/665889/180649357-3c7ea830-a2f8-43c9-9542-f33758e31827.png)

**Comment by shapoco** [comment]
move up/down functions added to context menu at https://github.com/shapoco/calctus/commit/bb7082b9de1ed20a9f161a2d3f177fabc864b795
