### ISSUE TITLE
"Create Timer" window inserts invalid timestamp on Korean locale

### ISSUE THREAD

**Issue by nulta** [shapoco/calctus#53]
![image](https://user-images.githubusercontent.com/35414766/236769318-06b843a0-776b-49ad-9a8b-f2ae56a32c8a.png)

![image](https://user-images.githubusercontent.com/35414766/236769364-fc805505-3098-42e8-a649-565e1597e3bb.png)

----

*Note: Korean Windows uses `YYYY-MM-DD` format by default*

![image](https://user-images.githubusercontent.com/35414766/236769498-a29bd4b0-28c7-4f22-afef-ee7db81cd214.png)

![image](https://user-images.githubusercontent.com/35414766/236770800-b6e0b47b-cdb5-4960-b980-d700c60e7f5a.png)

----

In Korean locale, "Create Timer" window inserts `#YYYY-MM-DD hh:mm:ss#` instead of `#YYYY/MM/DD hh:mm:ss#`, causing the parser to think it as a invalid color string.

**Comment by shapoco** [comment]
Thanks for pointing that out. This issue will be fixed in the next version.

**Comment by shapoco** [comment]
Reflected in v0.3.8534.27378-beta.
