### ISSUE TITLE
Win+key hotkeys don't work, only combinations(win+shift+key, etc)

### ISSUE THREAD

**Issue by Spirit532** [shapoco/calctus#55]
When you try using the windows key as the only hotkey condition(win+C), it doesn't work.
It works if used as an extra condition(e.g. win+shift+C), but not on its own.
This is on Windows 10.

**Comment by shapoco** [comment]
I could not do that in my environment either. Maybe Win+C is reserved at the system level.
Try using other key combinations or additional tools such as AutoHotkey.
https://superuser.com/questions/1291976/reuse-winc-shortcut-after-disabling-cortana-in-windows-10-1703
