### ISSUE TITLE
solve() lags with some operators

### ISSUE THREAD

**Issue by nulta** [shapoco/calctus#66]
## fraction operator
1. type `solve(x = 4$x, x)` in any row
2. now Calctus lags with _every_ keystrokes

`solve(x = 4$x + 2$x, x)` makes more lag. `solve(x = 4/x, x)` does not cause lag. 

## rand()
1. type `solve(rand()+rand()+rand()+x = 5, x)` in any row
2. now Calctus lags with _every_ keystrokes

## log2()
1. type `solve(log2(x) = 10, x)` in any row
2. Calctus hangs for some seconds
3. now Calctus lags with _every_ keystrokes

**Comment by shapoco** [comment]
Thanks for pointing that out.
The performance of solve(fraction) and solve(log2()) will be improved in the next version.
solve(rand()+rand()+rand()+...) is not planned to be fixed because of its uncommon usage.

**Comment by shapoco** [comment]
The changes were reflected in v0.5.8569.27359-alpha.
