### ISSUE TITLE
Option for Settings.cfg Location

### ISSUE THREAD

**Issue by Riajyuu** [shapoco/calctus#85]
I tried to take this app with my Onedrive between PCs but later find out Settings.cfg is store in %appdata%.
Is it possible to add an option to write setting file under same folder, aka relative path?

**Comment by shapoco** [comment]
From the next version, configuration files can be placed in the same directory as the executable file.

**Comment by shapoco** [comment]
This issue has been reflected in v0.6.
https://github.com/shapoco/calctus/releases/tag/v0.6.8857.6956-beta
