### ISSUE TITLE
Add color theme import support

### ISSUE THREAD

**Issue by Nigh** [shapoco/calctus#86]
It would nice to have ability import and export color theme files, that will make color theme sharing easier.

**Comment by shapoco** [comment]
Calctus settings are usually stored in the following file.

`C:\Users\<UserName>\AppData\Roaming\Shapoco\Calctus\Settings.cfg`

You can open this file in a text editor and copy and paste the lines beginning with `Appearance_Color_` to transfer the color settings from other environments.

It is recommended that you backup this file before you work on it, as incorrect editing may result in loss of settings.
