### ISSUE TITLE
桁区切りの追加

### ISSUE THREAD

**Issue by yukimaru73** [shapoco/calctus#91]
バイナリ(2進数)表記を指定した時に、設定より任意の桁をカンマ等の記号で区切って表示できるようにしていただけると非常に助かります。
16桁の出力の場合、
0b1111,1010,1100,0011
のように出力できるよう設定項目を追加していただきたいです。

**Comment by shapoco** [comment]
カンマは別の意味で予約されているため、スペースで区切って表示する機能を次バージョンからサポートします。

**Comment by shapoco** [comment]
This issue has been reflected in v0.6.
https://github.com/shapoco/calctus/releases/tag/v0.6.8857.6956-beta
